server:
  port: 8300
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wzhjqeds/springcloud-config-centre.git
          username: wzhjqeds
          password: zjg_303zjg
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8302/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      